# Generated by Django 3.2.5 on 2021-10-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayMap',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('subwayline', models.CharField(blank=True, max_length=17, null=True)),
                ('stationname', models.CharField(blank=True, max_length=39, null=True)),
                ('route1', models.CharField(blank=True, max_length=2, null=True)),
                ('route2', models.CharField(blank=True, max_length=2, null=True)),
                ('route3', models.CharField(blank=True, max_length=2, null=True)),
                ('route4', models.CharField(blank=True, max_length=2, null=True)),
                ('route5', models.CharField(blank=True, max_length=2, null=True)),
                ('route6', models.CharField(blank=True, max_length=2, null=True)),
                ('route7', models.CharField(blank=True, max_length=2, null=True)),
                ('route8', models.CharField(blank=True, max_length=2, null=True)),
                ('route9', models.CharField(blank=True, max_length=2, null=True)),
                ('route10', models.CharField(blank=True, max_length=2, null=True)),
                ('route11', models.CharField(blank=True, max_length=2, null=True)),
                ('entrancetype', models.CharField(blank=True, max_length=13, null=True)),
                ('entry', models.BooleanField(blank=True, null=True)),
                ('ada', models.BooleanField(blank=True, null=True)),
                ('freecrossover', models.BooleanField(blank=True, null=True)),
                ('entrancelat', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('entrancelong', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'subway',
            },
        ),
    ]
